version: 2

updates:
  - package-ecosystem: 'npm'
    directory: './'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 20
    target-branch: 'main'
    commit-message:
      prefix: 'Node Package Update: '
    commit-prefix: 'Node Package Update: '
