name: Bug report
description: Create a report to help us improve
title: '🐞 • '
labels:
  - bug

body:
  - type: dropdown
    attributes:
      label: 🧬 Type of Action
      options:
        - "**🔥 Hotfix**"
        - "🩹 Fix"

  - type: textarea
    attributes:
      label: "🐛 Describe the bug"
      description: A clear and concise description of what the bug is.
      placeholder: "What happened? What did you expect to happen?"

  - type: textarea
    attributes:
      label: "🔍 To Reproduce"
      description: Steps to reproduce the behavior.
      placeholder: | 
        1. Step one
        2. Step two
        3. Step three

  - type: textarea
    attributes:
      label: "🎯 Expected behavior"
      description: A clear and concise description of what you expected to happen.
      placeholder: "What did you expect to see?"

  - type: textarea
    attributes:
      label: "🖼️ Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop your screenshots here."

  - type: textarea
    attributes:
      label: "💻 System"
      description: "Details about your environment."
      placeholder: |
        - React version:  e.g. 16.8.0
        - Browser:  e.g. Chrome/firefox/safari
        - Operating System:   e.g. Linux/MacOS/Windows
        - Additional libraries or dependencies: e.g. Redux, React Router, etc.

  - type: textarea
    attributes:
      label: "📝 Additional context"
      description: Add any other context about the problem here.
      placeholder: "Any additional information that may help us understand the issue."